<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/9/24 0024
 * Time: 16:16
 */

namespace Test;

use EasySwoole\Redis\Client;
use PHPUnit\Framework\TestCase;

class BaseTest extends TestCase
{
    /**
     * @var $client Client
     */
    protected $client;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $client = new Client('127.0.0.1', 6379);
        $client->connect();
        $this->client = $client;
    }

    function testRecv()
    {
        $this->client->sendCommand(['set', 'a', '1']);
        $recv = $this->client->recv();
        $this->assertEquals('OK', $recv->getData());

        $this->client->sendCommand(['st', 'a', '1']);
        $recv = $this->client->recv();
        $this->assertEquals('-1', $recv->getStatus());

        $num = 1;
        $this->client->sendCommand(['set', 'b', $num]);
        $this->client->recv();
        $this->client->sendCommand(['incr', 'b']);
        $recv = $this->client->recv();
        $this->assertEquals('0', $recv->getStatus());
        $this->assertEquals($num + 1, $recv->getData());


        $this->client->sendCommand(['set', "a1", "a \r\n b \r\n 123456 \r\na"]);
        $this->client->recv();
        $this->client->sendCommand(['get', "a1"]);
        $recv = $this->client->recv();
        $this->assertEquals("a \r\n b \r\n 123456 \r\na", $recv->getData());


        $this->client->sendCommand(['del', "listA"]);
        $this->client->recv();
        $this->client->sendCommand(['sadd', "listA", 1]);
        $this->client->recv();
        $this->client->sendCommand(['sadd', "listA", 'a']);
        $this->client->recv();
        $this->client->sendCommand(['sadd', "listA", null]);
        $this->client->recv();
        $this->client->sendCommand(['sadd', "listA", "1\r\n 2\r\n a\r\nf"]);
        $this->client->recv();
        $this->client->sendCommand(['sadd', "listA", " "]);
        $this->client->recv();

        $this->client->sendCommand(['smembers', "listA"]);
        $recv = $this->client->recv();
        $this->assertEquals(5, count($recv->getData()));


    }


}
